services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}  # Use variable from .env
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}  # Use variable from .env
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  fastapi-app:
    build:
      context: ./
      dockerfile: ./fastapi-app/Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - data:/app/data/
    networks:
      - app-network

  streamlit-app:
    build:
      context: ./streamlit-app
    ports:
      - "8501:8501"
    networks:
      - app-network

volumes:
  mongo_data:
  data:

networks:
  app-network: